### PR TITLE
Creating my first GIT stuff :)

### PR DESCRIPTION
**Pull request by ThePro-gammer**

### CODE REVIEW

**Comment by Rouvik** [comment]
What's so special in it?

**Comment by ThePro-gammer** [comment]
Nothing special.

**Comment by Rouvik** [comment]
Printin string sucks

**Comment by Rouvik** [comment]
All right I am doing it

**Comment by ThePro-gammer** [comment]
As life itself doesn't.

**Comment by ThePro-gammer** [comment]
> All right I am doing it

Do what??

**Pull request merged**
